select 
PRESENTMENT_REQUEST_KEY, 
PRESENTMENT_KEY, 
PRESENTMENT_REQUEST_REASON_KEY, 
FORMAT(CAST(DATE_ENTERED AS DATETIME), N'yyyy-MM-dd HH:mm:ss') AS DATE_ENTERED, 
PRESENTMENT_PAYMENT_METHOD_KEY, 
AMT, 
COLLECTION_PAYMENT_NUMBER, 
FEE_PAYMENT_NUMBER, 
STATEMENT_ID, 
LOAN_PAYMENT_KEY 
FROM dbo.PresentmentRequest
WHERE CAST(DATE_ENTERED AS DATE) = CAST('{asOfDate}' as DATE)