# from export_mssql_to_csv import batch_size

sql_queries = {
    'CREO_MessageDeliveryStatus_Batch': f"""
    SELECT
        MESSAGE_DELIVERY_STATUS_KEY
        ,MESSAGE_KEY
        ,DELIVERY_STATUS_KEY
        ,DATE_ENTERED
        ,Replace(Replace(DETAIL,CHAR(10),''),CHAR(13),'') AS DETAIL
    FROM CREO.[dbo].[MessageDeliveryStatus]
    ORDER BY MESSAGE_DELIVERY_STATUS_KEY
    """,

    # 'CREO_Message_Batch': f"""
    # SELECT
    #     MESSAGE_KEY, [SUBJECT], DATE_ENTERED, DATE_SENT, 
    #     Replace(Replace(EXCEPTION,CHAR(10),''),CHAR(13),'') AS EXCEPTION,
    #     CONTAINER_KEY, COMMUNICATION_MAILING_KEY, TEMPLATE_KEY, IS_PRODUCTION, DATASET_ROW_KEY, [SERVER], MESSAGE_ID, [TYPE], NUM_EXCEPTIONS, DELIVERY_STATUS_KEY, IN_REPLY_TO_MESSAGE_KEY, DIRECTION, SEND_AFTER, SEND_AFTER_MESSAGE_KEY, IS_FINISHED, HEADERS, VENDOR_ID
    # FROM CREO.[dbo].[Message]
    # ORDER BY MESSAGE_KEY
    # """,

    'CREO_Message_Batch': f"""
    SELECT
        MESSAGE_KEY, 
        REPLACE([SUBJECT], CHAR(237), N'i') AS [SUBJECT],
        DATE_ENTERED, DATE_SENT, 
        Replace(Replace(EXCEPTION,CHAR(10),''),CHAR(13),'') AS EXCEPTION,
        CONTAINER_KEY, COMMUNICATION_MAILING_KEY, TEMPLATE_KEY, IS_PRODUCTION, DATASET_ROW_KEY, [SERVER], MESSAGE_ID, [TYPE], NUM_EXCEPTIONS, DELIVERY_STATUS_KEY, IN_REPLY_TO_MESSAGE_KEY, DIRECTION, SEND_AFTER, SEND_AFTER_MESSAGE_KEY, IS_FINISHED, 
        Replace(Replace(HEADERS,CHAR(10),''),CHAR(13),'') AS HEADERS,
        VENDOR_ID
    FROM CREO.[dbo].[Message]
    ORDER BY MESSAGE_KEY
    """,

    # 'key': 'value',

}

