select 
INSURANCE_ENROLLMENT_KEY, 
LOAN_KEY, 
CAST(DATE_ENTERED AS DATE) as DATE_ENTERED, 
ENTERED_BY, 
CANCEL_LOAN_PAYMENT_KEY, 
INSURANCE_CANCEL_REASON_KEY, 
INSURANCE_CANCEL_IN_GRACE_PERIOD 
FROM dbo.InsuranceEnrollment
WHERE CAST(DATE_ENTERED AS DATE) = CAST('{asOfDate}' as DATE)