select 
LOAN_FUNDING_KEY, 
LOAN_KEY, 
APPROVED_LOAN_PAYMENT_KEY, 
FUNDING_AMT, 
REQUESTED_FUNDING_METHOD_KEY, 
ACTUAL_FUNDING_METHOD_KEY, 
FUNDING_STATUS_KEY, 
FUNDING_LOAN_PAYMENT_KEY, 
VOID_LOAN_PAYMENT_KEY, 
FORMAT(CAST(REQUESTED_FUNDING_METHOD_CHANGE_DATE AS DATETIME), N'yyyy-MM-dd HH:mm:ss'), 
FORMAT(CAST(HOLD_UNTIL AS DATETIME), N'yyyy-MM-dd HH:mm:ss'), 
FORMAT(CAST(DATE_ENTERED AS DATETIME), N'yyyy-MM-dd HH:mm:ss'), 
CAST(IS_SPLIT_FUNDING AS INT), 
FUNDING_TYPE_KEY 
FROM dbo.LoanFunding
WHERE CAST(DATE_ENTERED AS DATE) = CAST('{asOfDate}' as DATE)