

-- // TABLE: Log
-- !! DROP TABLE IF EXISTS STG.CREO_LOG_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_LOG_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    LOG_KEY BIGINT NOT NULL ,
	ACTION VARCHAR(8000) NULL COLLATE 'en-ci',
	DESCRIPTION VARCHAR(8000) NULL COLLATE 'en-ci',
	IP_ADDRESS VARCHAR(8000) NULL COLLATE 'en-ci',
	USERNAME VARCHAR(8000) NULL COLLATE 'en-ci',
	RULE_KEY INT NULL ,
	TEMPLATE_KEY INT NULL ,
	PACKAGE_KEY INT NULL ,
	CONTAINER_KEY INT NULL ,
	MESSAGE_KEY BIGINT NULL ,
	CAMPAIGN_KEY INT NULL ,
	COMMUNICATION_KEY INT NULL ,
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL ,
	SERVER VARCHAR(8000) NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Log_HIST LIMIT 10;



-- // TABLE: Message
-- !! DROP TABLE IF EXISTS STG.CREO_MESSAGE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGE_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_KEY BIGINT NOT NULL ,
	SUBJECT VARCHAR(8000) NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL ,
	DATE_SENT TIMESTAMP_LTZ NULL ,
	EXCEPTION VARCHAR(8000) NULL COLLATE 'en-ci',
	CONTAINER_KEY INT NULL ,
	COMMUNICATION_MAILING_KEY INT NULL ,
	TEMPLATE_KEY INT NULL ,
	IS_PRODUCTION BOOLEAN NOT NULL ,
	DATASET_ROW_KEY BIGINT NULL ,
	SERVER VARCHAR(8000) NULL COLLATE 'en-ci',
	MESSAGE_ID VARCHAR(36) NOT NULL ,
	TYPE SMALLINT NULL ,
	NUM_EXCEPTIONS INT NOT NULL ,
	DELIVERY_STATUS_KEY INT NULL ,
	IN_REPLY_TO_MESSAGE_KEY BIGINT NULL ,
	DIRECTION SMALLINT NOT NULL ,
	SEND_AFTER TIMESTAMP_LTZ NULL ,
	SEND_AFTER_MESSAGE_KEY BIGINT NULL ,
	IS_FINISHED BOOLEAN NOT NULL ,
	HEADERS VARCHAR(8000) NULL COLLATE 'en-ci',
	VENDOR_ID VARCHAR(8000) NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Message_HIST LIMIT 10;



-- // TABLE: Package
-- !! DROP TABLE IF EXISTS STG.CREO_PACKAGE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_PACKAGE_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    PACKAGE_KEY INT NOT NULL ,
	CONTAINER_KEY INT NOT NULL ,
	DATE_PUBLISHED TIMESTAMP_LTZ NULL ,
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL ,
	HASH VARCHAR(8000) NULL COLLATE 'en-ci',
	COMMIT_MESSAGE VARCHAR(8000) NULL COLLATE 'en-ci',
	PUBLISHED_BY VARCHAR(8000) NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Package_HIST LIMIT 10;



-- // TABLE: Rule
-- !! DROP TABLE IF EXISTS STG.CREO_RULE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_RULE_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    RULE_KEY INT NOT NULL ,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	PARAMETER_NAME VARCHAR(8000) NULL COLLATE 'en-ci',
	TYPE INT NOT NULL ,
	DATE_START TIMESTAMP_LTZ NULL ,
	DATE_END TIMESTAMP_LTZ NULL ,
	ENABLED BOOLEAN NOT NULL ,
	IS_DELETED BOOLEAN NOT NULL ,
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL ,
	DEFINITION VARCHAR(8000) NULL COLLATE 'en-ci',
	WEIGHT INT NULL ,
	CONTAINER_KEY INT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Rule_HIST LIMIT 10;



-- // TABLE: Config
-- !! DROP TABLE IF EXISTS STG.CREO_CONFIG_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_CONFIG_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    CONFIG_KEY INT NOT NULL ,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	VALUE VARCHAR(8000) NOT NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Config_HIST LIMIT 10;



-- // TABLE: Template
-- !! DROP TABLE IF EXISTS STG.CREO_TEMPLATE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_TEMPLATE_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    TEMPLATE_KEY INT NOT NULL ,
	PATH VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	CONTENT VARIANT NULL ,
	TYPE SMALLINT NOT NULL ,
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL ,
	DESCRIPTION VARCHAR(8000) NULL COLLATE 'en-ci',
	BASE_TEMPLATE_KEY INT NULL ,
	CONTENT_HASH VARCHAR(8000) NULL COLLATE 'en-ci',
	NOTES VARCHAR(8000) NULL COLLATE 'en-ci',
	EDITED_BY VARCHAR(8000) NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Template_HIST LIMIT 10;



-- // TABLE: Container
-- !! DROP TABLE IF EXISTS STG.CREO_CONTAINER_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_CONTAINER_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    CONTAINER_KEY INT NOT NULL ,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL ,
	IS_DELETED BOOLEAN NOT NULL ,
	IS_DEPRECATED BOOLEAN NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Container_HIST LIMIT 10;



-- // TABLE: PackageTemplate
-- !! DROP TABLE IF EXISTS STG.CREO_PACKAGETEMPLATE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_PACKAGETEMPLATE_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    PACKAGE_KEY INT NOT NULL ,
	TEMPLATE_KEY INT NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_PackageTemplate_HIST LIMIT 10;



-- // TABLE: TemplateRule
-- !! DROP TABLE IF EXISTS STG.CREO_TEMPLATERULE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_TEMPLATERULE_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    TEMPLATE_KEY INT NOT NULL ,
	RULE_KEY INT NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_TemplateRule_HIST LIMIT 10;



-- // TABLE: Campaign
-- !! DROP TABLE IF EXISTS STG.CREO_CAMPAIGN_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_CAMPAIGN_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    CAMPAIGN_KEY INT NOT NULL ,
	NAME VARCHAR(8000) NULL COLLATE 'en-ci',
	CONTAINER_KEY INT NOT NULL ,
	DATASET_KEY INT NULL ,
	IS_DELETED BOOLEAN NOT NULL ,
	IS_ENABLED BOOLEAN NOT NULL ,
	IS_PRODUCTION BOOLEAN NOT NULL ,
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL ,
	AUTO_START_PATTERN_FOR_DATASET VARCHAR(8000) NULL COLLATE 'en-ci',
	DISALLOW_RENAME BOOLEAN NOT NULL ,
	IS_SEED_LIST_ENABLED BOOLEAN NOT NULL ,
	SEED_LIST_DATASET_KEY INT NULL ,
	SEED_LIST_FREQUENCY_DAYS INT NULL ,
	SEED_LIST_START_TIME TIME NULL ,
	SEED_LIST_SENT_AT TIMESTAMP_LTZ NULL ,
	SEED_LIST_WILL_SEND_AT TIMESTAMP_LTZ NULL ,
	CAMPAIGN_TYPE_KEY INT NULL ,
	IS_PRIORITY BOOLEAN NOT NULL ,
	SEND_WITHOUT_PREFERENCES BOOLEAN NOT NULL ,
	REASON_DISABLED VARCHAR(8000) NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Campaign_HIST LIMIT 10;



-- // TABLE: User
-- !! DROP TABLE IF EXISTS STG.CREO_USER_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_USER_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    USER_KEY INT NOT NULL ,
	USERNAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_User_HIST LIMIT 10;



-- // TABLE: Communication
-- !! DROP TABLE IF EXISTS STG.CREO_COMMUNICATION_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_COMMUNICATION_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    COMMUNICATION_KEY INT NOT NULL ,
	CAMPAIGN_KEY INT NOT NULL ,
	IS_ENABLED BOOLEAN NOT NULL ,
	IS_DELETED BOOLEAN NOT NULL ,
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL ,
	START_TIME TIME NULL ,
	END_TIME TIME NULL ,
	LIMIT_PER_HOUR INT NULL ,
	DATE_START TIMESTAMP_LTZ NULL ,
	DATE_END TIMESTAMP_LTZ NULL ,
	WEEKDAYS INT NULL ,
	TEMPLATE_PATH VARCHAR(8000) NULL COLLATE 'en-ci',
	CONFIG_PATH VARCHAR(8000) NULL COLLATE 'en-ci',
	TYPE SMALLINT NOT NULL ,
	ENABLE_QUEUE_BEFORE_DATE_START BOOLEAN NULL ,
	IS_PRODUCTION BOOLEAN NOT NULL ,
	Provider VARCHAR(8000) NULL COLLATE 'en-ci',
	REASON_DISABLED VARCHAR(8000) NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Communication_HIST LIMIT 10;



-- // TABLE: CommunicationMailing
-- !! DROP TABLE IF EXISTS STG.CREO_COMMUNICATIONMAILING_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_COMMUNICATIONMAILING_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    COMMUNICATION_MAILING_KEY INT NOT NULL ,
	COMMUNICATION_KEY INT NOT NULL ,
	SENT INT NOT NULL ,
	QUEUED INT NOT NULL ,
	TOTAL INT NOT NULL ,
	EXCEPTION INT NOT NULL ,
	STATUS INT NOT NULL ,
	IS_STALE BOOLEAN NOT NULL ,
	DATE_STARTED TIMESTAMP_LTZ NULL ,
	DATE_COMPLETED TIMESTAMP_LTZ NULL ,
	DATE_UPDATED TIMESTAMP_LTZ NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_CommunicationMailing_HIST LIMIT 10;



-- // TABLE: Dataset
-- !! DROP TABLE IF EXISTS STG.CREO_DATASET_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_DATASET_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DATASET_KEY INT NOT NULL ,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL ,
	IS_DELETED BOOLEAN NOT NULL ,
	CONTAINER_KEY INT NOT NULL ,
	ATTRIBUTES INT NOT NULL ,
	ROW_COUNT INT NULL ,
	ROW_COUNT_UPDATED TIMESTAMP_LTZ NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Dataset_HIST LIMIT 10;



-- // TABLE: DatasetCell
-- !! DROP TABLE IF EXISTS STG.CREO_DATASETCELL_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_DATASETCELL_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DATASET_ROW_KEY BIGINT NOT NULL ,
	DATASET_COLUMN_KEY INT NOT NULL ,
	DATASET_VALUE_KEY BIGINT NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_DatasetCell_HIST LIMIT 10;



-- // TABLE: DatasetColumn
-- !! DROP TABLE IF EXISTS STG.CREO_DATASETCOLUMN_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_DATASETCOLUMN_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DATASET_COLUMN_KEY INT NOT NULL ,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_DatasetColumn_HIST LIMIT 10;



-- // TABLE: DatasetRow
-- !! DROP TABLE IF EXISTS STG.CREO_DATASETROW_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_DATASETROW_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DATASET_ROW_KEY BIGINT NOT NULL ,
	DATASET_KEY INT NOT NULL ,
	HAS_MESSAGE BOOLEAN NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_DatasetRow_HIST LIMIT 10;



-- // TABLE: DatasetValue
-- !! DROP TABLE IF EXISTS STG.CREO_DATASETVALUE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_DATASETVALUE_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DATASET_VALUE_KEY BIGINT NOT NULL ,
	VALUE VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	VALUE_HASH BINARY(8000) NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_DatasetValue_HIST LIMIT 10;



-- // TABLE: Datasource
-- !! DROP TABLE IF EXISTS STG.CREO_DATASOURCE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_DATASOURCE_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DATASOURCE_KEY INT NOT NULL ,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	DEFINITION VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	TYPE INT NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Datasource_HIST LIMIT 10;



-- // TABLE: DeliveryStatus
-- !! DROP TABLE IF EXISTS STG.CREO_DELIVERYSTATUS_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_DELIVERYSTATUS_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DELIVERY_STATUS_KEY INT NOT NULL ,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	REFERENCE VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	LIMIT_PER_MESSAGE INT NULL ,
	IS_ERROR BOOLEAN NOT NULL ,
	IS_FINAL BOOLEAN NOT NULL ,
	DESCRIPTION VARCHAR(8000) NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_DeliveryStatus_HIST LIMIT 10;



-- // TABLE: Emoji
-- !! DROP TABLE IF EXISTS STG.CREO_EMOJI_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_EMOJI_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    EMOJI_KEY INT NOT NULL ,
	SHORT_NAME VARCHAR(8000) NULL COLLATE 'en-ci',
	DESCRIPTION VARCHAR(8000) NULL COLLATE 'en-ci',
	CODE VARCHAR(8000) NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Emoji_HIST LIMIT 10;



-- // TABLE: Folder
-- !! DROP TABLE IF EXISTS STG.CREO_FOLDER_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_FOLDER_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    FOLDER_KEY INT NOT NULL ,
	NAME VARCHAR(8000) NULL COLLATE 'en-ci',
	CONTAINER_KEY INT NOT NULL ,
	PARENT_FOLDER_KEY INT NULL ,
	IS_CATCH_ALL BOOLEAN NOT NULL ,
	DELETE_AFTER_DAYS INT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Folder_HIST LIMIT 10;



-- // TABLE: MessageDeliveryStatus
-- !! DROP TABLE IF EXISTS STG.CREO_MESSAGEDELIVERYSTATUS_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGEDELIVERYSTATUS_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_DELIVERY_STATUS_KEY BIGINT NOT NULL ,
	MESSAGE_KEY BIGINT NOT NULL ,
	DELIVERY_STATUS_KEY INT NOT NULL ,
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL ,
	DETAIL VARCHAR(8000) NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_MessageDeliveryStatus_HIST LIMIT 10;



-- // TABLE: FolderContact
-- !! DROP TABLE IF EXISTS STG.CREO_FOLDERCONTACT_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_FOLDERCONTACT_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    CONTACT_KEY INT NOT NULL ,
	FOLDER_KEY INT NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_FolderContact_HIST LIMIT 10;



-- // TABLE: FolderMessage
-- !! DROP TABLE IF EXISTS STG.CREO_FOLDERMESSAGE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_FOLDERMESSAGE_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_KEY BIGINT NOT NULL ,
	FOLDER_KEY INT NOT NULL ,
	LOCKED_BY VARCHAR(8000) NULL COLLATE 'en-ci',
	IS_READ BOOLEAN NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_FolderMessage_HIST LIMIT 10;



-- // TABLE: Parameter
-- !! DROP TABLE IF EXISTS STG.CREO_PARAMETER_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_PARAMETER_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    PARAMETER_KEY INT NOT NULL ,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	DEFINITION VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	DATASOURCE_KEY INT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Parameter_HIST LIMIT 10;



-- // TABLE: MessageStatusQueue
-- !! DROP TABLE IF EXISTS STG.CREO_MESSAGESTATUSQUEUE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGESTATUSQUEUE_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_STATUS_QUEUE_KEY BIGINT NOT NULL ,
	DATA VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	DETAIL VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	TYPE INT NOT NULL ,
	ENTERED_AT datetime NOT NULL ,
	CONTAINER_KEY INT NULL ,
	SERVER VARCHAR(8000) NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_MessageStatusQueue_HIST LIMIT 10;



-- // TABLE: Global
-- !! DROP TABLE IF EXISTS STG.CREO_GLOBAL_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_GLOBAL_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    APP_VERSION DECIMAL(38,38) NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Global_HIST LIMIT 10;



-- // TABLE: CampaignType
-- !! DROP TABLE IF EXISTS STG.CREO_CAMPAIGNTYPE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_CAMPAIGNTYPE_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    CAMPAIGN_TYPE_KEY INT NOT NULL ,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_CampaignType_HIST LIMIT 10;



-- // TABLE: TempMessage
-- !! DROP TABLE IF EXISTS STG.CREO_TEMPMESSAGE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_TEMPMESSAGE_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    TEMP_MESSAGE_KEY INT NOT NULL ,
	Json VARCHAR(8000) NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_TempMessage_HIST LIMIT 10;



-- // TABLE: ContactType
-- !! DROP TABLE IF EXISTS STG.CREO_CONTACTTYPE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_CONTACTTYPE_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    CONTACT_TYPE_KEY SMALLINT NOT NULL ,
	DESCRIPTION VARCHAR(8000) NOT NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_ContactType_HIST LIMIT 10;



-- // TABLE: ApprovalRequest
-- !! DROP TABLE IF EXISTS STG.CREO_APPROVALREQUEST_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_APPROVALREQUEST_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    APPROVAL_REQUEST_KEY INT NOT NULL ,
	STATUS INT NOT NULL ,
	ENTERED_AT TIMESTAMP_LTZ NOT NULL ,
	PACKAGE_KEY INT NOT NULL ,
	REQUESTED_BY VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	PROCESSED_BY VARCHAR(8000) NULL COLLATE 'en-ci',
	COMMIT_MESSAGE VARCHAR(8000) NULL COLLATE 'en-ci',
	PROCESSED_AT TIMESTAMP_LTZ NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_ApprovalRequest_HIST LIMIT 10;



-- // TABLE: DeadMessages
-- !! DROP TABLE IF EXISTS STG.CREO_DEADMESSAGES_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_DEADMESSAGES_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_KEY BIGINT NOT NULL ,
	SUBJECT VARCHAR(8000) NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL ,
	DATE_SENT TIMESTAMP_LTZ NULL ,
	EXCEPTION VARCHAR(8000) NULL COLLATE 'en-ci',
	CONTAINER_KEY INT NULL ,
	COMMUNICATION_MAILING_KEY INT NULL ,
	TEMPLATE_KEY INT NULL ,
	IS_PRODUCTION BOOLEAN NOT NULL ,
	DATASET_ROW_KEY BIGINT NULL ,
	SERVER VARCHAR(8000) NULL COLLATE 'en-ci',
	MESSAGE_ID VARCHAR(36) NOT NULL ,
	TYPE SMALLINT NULL ,
	NUM_EXCEPTIONS INT NOT NULL ,
	DELIVERY_STATUS_KEY INT NULL ,
	IN_REPLY_TO_MESSAGE_KEY BIGINT NULL ,
	DIRECTION SMALLINT NOT NULL ,
	SEND_AFTER TIMESTAMP_LTZ NULL ,
	SEND_AFTER_MESSAGE_KEY BIGINT NULL ,
	IS_FINISHED BOOLEAN NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_DeadMessages_HIST LIMIT 10;



-- // TABLE: MessageContactType
-- !! DROP TABLE IF EXISTS STG.CREO_MESSAGECONTACTTYPE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGECONTACTTYPE_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_CONTACT_TYPE_KEY INT NOT NULL ,
	DESCRIPTION VARCHAR(8000) NOT NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_MessageContactType_HIST LIMIT 10;



-- // TABLE: ApprovalRequestItem
-- !! DROP TABLE IF EXISTS STG.CREO_APPROVALREQUESTITEM_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_APPROVALREQUESTITEM_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    APPROVAL_REQUEST_ITEM_KEY INT NOT NULL ,
	APPROVAL_REQUEST_KEY INT NOT NULL ,
	TEMPLATE_KEY INT NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_ApprovalRequestItem_HIST LIMIT 10;



-- // TABLE: MessageType
-- !! DROP TABLE IF EXISTS STG.CREO_MESSAGETYPE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGETYPE_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_TYPE_KEY SMALLINT NOT NULL ,
	DESCRIPTION VARCHAR(8000) NOT NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_MessageType_HIST LIMIT 10;



-- // TABLE: ConfigHistory
-- !! DROP TABLE IF EXISTS STG.CREO_CONFIGHISTORY_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_CONFIGHISTORY_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    CONFIG_HISTORY_KEY INT NOT NULL ,
	CONFIG_KEY INT NOT NULL ,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	OLD_VALUE VARCHAR(8000) NULL COLLATE 'en-ci',
	CHANGED_BY VARCHAR(8000) NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_ConfigHistory_HIST LIMIT 10;



-- // TABLE: TemplateType
-- !! DROP TABLE IF EXISTS STG.CREO_TEMPLATETYPE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_TEMPLATETYPE_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    TEMPLATE_TYPE_KEY SMALLINT NOT NULL ,
	DESCRIPTION VARCHAR(8000) NOT NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_TemplateType_HIST LIMIT 10;



-- // TABLE: Contact
-- !! DROP TABLE IF EXISTS STG.CREO_CONTACT_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_CONTACT_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    CONTACT_KEY INT NOT NULL ,
	NAME VARCHAR(8000) NULL COLLATE 'en-ci',
	ADDRESS VARCHAR(8000) NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL ,
	CONTACT_TYPE SMALLINT NOT NULL ,
	IS_EXPIRED BOOLEAN NOT NULL ,
	NUM_ERRORS INT NOT NULL ,
	IS_INVALID BOOLEAN NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Contact_HIST LIMIT 10;



-- // TABLE: MessageContact
-- !! DROP TABLE IF EXISTS STG.CREO_MESSAGECONTACT_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGECONTACT_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_CONTACT_KEY INT NOT NULL ,
	MESSAGE_KEY BIGINT NOT NULL ,
	CONTACT_KEY INT NOT NULL ,
	TYPE INT NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_MessageContact_HIST LIMIT 10;



-- // TABLE: MessagePart
-- !! DROP TABLE IF EXISTS STG.CREO_MESSAGEPART_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGEPART_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_PART_KEY INT NOT NULL ,
	MESSAGE_KEY BIGINT NULL ,
	CONTENT_TYPE VARCHAR(8000) NULL COLLATE 'en-ci',
	FILENAME_ VARCHAR(8000) NULL COLLATE 'en-ci',
	DATA VARIANT NULL ,
	IS_COMPRESSED BOOLEAN NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_MessagePart_HIST LIMIT 10;



-- // TABLE: MessageContactV2
-- !! DROP TABLE IF EXISTS STG.CREO_MESSAGECONTACTV2_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGECONTACTV2_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_CONTACT_KEY BIGINT NOT NULL ,
	MESSAGE_KEY BIGINT NOT NULL ,
	CONTACT_KEY INT NOT NULL ,
	TYPE INT NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_MessageContactV2_HIST LIMIT 10;



-- // TABLE: MessagePartV2
-- !! DROP TABLE IF EXISTS STG.CREO_MESSAGEPARTV2_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGEPARTV2_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_PART_KEY BIGINT NOT NULL ,
	MESSAGE_KEY BIGINT NULL ,
	CONTENT_TYPE VARCHAR(8000) NULL COLLATE 'en-ci',
	FILENAME_ VARCHAR(8000) NULL COLLATE 'en-ci',
	DATA VARIANT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_MessagePartV2_HIST LIMIT 10;



-- // TABLE: DeadMessages2
-- !! DROP TABLE IF EXISTS STG.CREO_DEADMESSAGES2_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_DEADMESSAGES2_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_KEY BIGINT NOT NULL ,
	SUBJECT VARCHAR(8000) NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL ,
	DATE_SENT TIMESTAMP_LTZ NULL ,
	EXCEPTION VARCHAR(8000) NULL COLLATE 'en-ci',
	CONTAINER_KEY INT NULL ,
	COMMUNICATION_MAILING_KEY INT NULL ,
	TEMPLATE_KEY INT NULL ,
	IS_PRODUCTION BOOLEAN NOT NULL ,
	DATASET_ROW_KEY BIGINT NULL ,
	SERVER VARCHAR(8000) NULL COLLATE 'en-ci',
	MESSAGE_ID VARCHAR(36) NOT NULL ,
	TYPE SMALLINT NULL ,
	NUM_EXCEPTIONS INT NOT NULL ,
	DELIVERY_STATUS_KEY INT NULL ,
	IN_REPLY_TO_MESSAGE_KEY BIGINT NULL ,
	DIRECTION SMALLINT NOT NULL ,
	SEND_AFTER TIMESTAMP_LTZ NULL ,
	SEND_AFTER_MESSAGE_KEY BIGINT NULL ,
	IS_FINISHED BOOLEAN NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_DeadMessages2_HIST LIMIT 10;



-- // TABLE: WebHook
-- !! DROP TABLE IF EXISTS STG.CREO_WEBHOOK_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_WEBHOOK_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    WEBHOOK_KEY INT NOT NULL ,
	CONTAINER_KEY INT NOT NULL ,
	TYPE INT NOT NULL ,
	URL VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	EVENT_NAME VARCHAR(8000) NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_WebHook_HIST LIMIT 10;



-- // TABLE: Message
-- !! DROP TABLE IF EXISTS STG.CREO_MESSAGE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGE_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_KEY BIGINT NOT NULL ,
	SUBJECT VARCHAR(8000) NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL ,
	DATE_SENT TIMESTAMP_LTZ NULL ,
	EXCEPTION VARCHAR(8000) NULL COLLATE 'en-ci',
	CONTAINER_KEY INTEGER NULL ,
	COMMUNICATION_MAILING_KEY INTEGER NULL ,
	TEMPLATE_KEY INTEGER NULL ,
	IS_PRODUCTION BOOLEAN NOT NULL ,
	DATASET_ROW_KEY BIGINT NULL ,
	SERVER VARCHAR(8000) NULL COLLATE 'en-ci',
	MESSAGE_ID VARCHAR(36) NOT NULL ,
	TYPE SMALLINT NULL ,
	NUM_EXCEPTIONS INTEGER NOT NULL ,
	DELIVERY_STATUS_KEY INTEGER NULL ,
	IN_REPLY_TO_MESSAGE_KEY BIGINT NULL ,
	DIRECTION SMALLINT NOT NULL ,
	SEND_AFTER TIMESTAMP_LTZ NULL ,
	SEND_AFTER_MESSAGE_KEY BIGINT NULL ,
	IS_FINISHED BOOLEAN NOT NULL ,
	HEADERS VARCHAR(8000) NULL COLLATE 'en-ci',
	VENDOR_ID VARCHAR(8000) NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Message_HIST LIMIT 10;



-- // TABLE: DatasetRow
-- !! DROP TABLE IF EXISTS STG.CREO_DATASETROW_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_DATASETROW_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DATASET_ROW_KEY BIGINT NOT NULL ,
	DATASET_KEY INTEGER NOT NULL ,
	HAS_MESSAGE BOOLEAN NOT NULL 
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_DatasetRow_HIST LIMIT 10;



-- // TABLE: MessageContact
-- !! DROP TABLE IF EXISTS STG.CREO_MESSAGECONTACT_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGECONTACT_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_CONTACT_KEY INTEGER NOT NULL ,
	MESSAGE_KEY BIGINT NOT NULL ,
	CONTACT_KEY INTEGER NOT NULL ,
	TYPE INTEGER NOT NULL 
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_MessageContact_HIST LIMIT 10;



-- // TABLE: DatasetCell
-- !! DROP TABLE IF EXISTS STG.CREO_DATASETCELL_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_DATASETCELL_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DATASET_ROW_KEY BIGINT NOT NULL ,
	DATASET_COLUMN_KEY INTEGER NOT NULL ,
	DATASET_VALUE_KEY BIGINT NOT NULL 
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_DatasetCell_HIST LIMIT 10;



-- // TABLE: Global
-- !! DROP TABLE IF EXISTS STG.CREO_GLOBAL_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_GLOBAL_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    APP_VERSION DECIMAL(38,38) NOT NULL 
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_Global_HIST LIMIT 10;



-- // TABLE: MessageContactV2
-- !! DROP TABLE IF EXISTS STG.CREO_MESSAGECONTACTV2_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGECONTACTV2_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_CONTACT_KEY BIGINT NOT NULL ,
	MESSAGE_KEY BIGINT NOT NULL ,
	CONTACT_KEY INTEGER NOT NULL ,
	TYPE INTEGER NOT NULL 
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_MessageContactV2_HIST LIMIT 10;



-- // TABLE: MessageDeliveryStatus
-- !! DROP TABLE IF EXISTS STG.CREO_MESSAGEDELIVERYSTATUS_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGEDELIVERYSTATUS_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_DELIVERY_STATUS_KEY BIGINT NOT NULL ,
	MESSAGE_KEY BIGINT NOT NULL ,
	DELIVERY_STATUS_KEY INTEGER NOT NULL ,
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL ,
	DETAIL VARCHAR(8000) NULL COLLATE 'en-ci'
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_MessageDeliveryStatus_HIST LIMIT 10;



-- // TABLE: MessagePart
-- !! DROP TABLE IF EXISTS STG.CREO_MESSAGEPART_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGEPART_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_PART_KEY INTEGER NOT NULL ,
	MESSAGE_KEY BIGINT NULL ,
	CONTENT_TYPE VARCHAR(8000) NULL COLLATE 'en-ci',
	FILENAME_ VARCHAR(8000) NULL COLLATE 'en-ci',
	DATA VARIANT NULL ,
	IS_COMPRESSED BOOLEAN NOT NULL 
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_MessagePart_HIST LIMIT 10;



-- // TABLE: MessagePartV2
-- !! DROP TABLE IF EXISTS STG.CREO_MESSAGEPARTV2_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGEPARTV2_HIST ( 
    FILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_PART_KEY BIGINT NOT NULL ,
	MESSAGE_KEY BIGINT NULL ,
	CONTENT_TYPE VARCHAR(8000) NULL COLLATE 'en-ci',
	FILENAME_ VARCHAR(8000) NULL COLLATE 'en-ci',
	DATA VARIANT NULL 
);
-- // [STATUS=tbd] : SELECT * FROM STG.CREO_MessagePartV2_HIST LIMIT 10;

