USE SCHEMA { SF_DATABASE }.STG;

/*************************************************************************/
/* Note:																 */ 
/* 1. MUST USE 'CREATE TABLE IF NOT EXISTS'                              */
/* 2. DO NOT USE MASKING POLICIES - They will be applied separately      */
/*************************************************************************/

-- // TABLE 37: DatasetCell 
CREATE TABLE IF NOT EXISTS STG.CREO_DATASETCELL_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DATASET_ROW_KEY BIGINT NOT NULL,
	DATASET_COLUMN_KEY INT NOT NULL,
	DATASET_VALUE_KEY BIGINT NOT NULL
);

-- // TABLE 38: DatasetRow 
CREATE TABLE IF NOT EXISTS STG.CREO_DATASETROW_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DATASET_ROW_KEY BIGINT NOT NULL,
	DATASET_KEY INT NOT NULL,
	HAS_MESSAGE BOOLEAN NOT NULL
);

-- // TABLE 39: MessageContactV2 
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGECONTACTV2_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_CONTACT_KEY BIGINT NOT NULL,
	MESSAGE_KEY BIGINT NOT NULL,
	CONTACT_KEY INT NOT NULL,
	TYPE INT NOT NULL
);

-- // TABLE 40: PackageTemplate 
CREATE TABLE IF NOT EXISTS STG.CREO_PACKAGETEMPLATE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    PACKAGE_KEY INT NOT NULL,
	TEMPLATE_KEY INT NOT NULL
);
