USE SCHEMA {{ SF_DATABASE }}.STG;

/*************************************************************************/
/* Note:																 */ 
/* 1. MUST USE 'CREATE TABLE IF NOT EXISTS'                              */
/* 2. DO NOT USE MASKING POLICIES - They will be applied separately      */
/*************************************************************************/

-- // TABLE 1: ApprovalRequest 
CREATE TABLE IF NOT EXISTS STG.CREO_APPROVALREQUEST_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    APPROVAL_REQUEST_KEY INT NOT NULL,
	STATUS INT NOT NULL,
	ENTERED_AT TIMESTAMP_LTZ NOT NULL,
	PACKAGE_KEY INT NOT NULL,
	REQUESTED_BY VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	PROCESSED_BY VARCHAR(8000) NULL COLLATE 'en-ci',
	COMMIT_MESSAGE VARCHAR(8000) NULL COLLATE 'en-ci',
	PROCESSED_AT TIMESTAMP_LTZ NULL 
);

-- // TABLE 2: ApprovalRequestItem 
CREATE TABLE IF NOT EXISTS STG.CREO_APPROVALREQUESTITEM_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    APPROVAL_REQUEST_ITEM_KEY INT NOT NULL,
	APPROVAL_REQUEST_KEY INT NOT NULL,
	TEMPLATE_KEY INT NOT NULL 
);

-- // TABLE 3: Campaign 
CREATE TABLE IF NOT EXISTS STG.CREO_CAMPAIGN_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    CAMPAIGN_KEY INT NOT NULL,
	NAME VARCHAR(8000) NULL COLLATE 'en-ci',
	CONTAINER_KEY INT NOT NULL,
	DATASET_KEY INT NULL,
	IS_DELETED BOOLEAN NOT NULL,
	IS_ENABLED BOOLEAN NOT NULL,
	IS_PRODUCTION BOOLEAN NOT NULL,
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL,
	AUTO_START_PATTERN_FOR_DATASET VARCHAR(8000) NULL COLLATE 'en-ci',
	DISALLOW_RENAME BOOLEAN NOT NULL,
	IS_SEED_LIST_ENABLED BOOLEAN NOT NULL,
	SEED_LIST_DATASET_KEY INT NULL,
	SEED_LIST_FREQUENCY_DAYS INT NULL,
	SEED_LIST_START_TIME TIME NULL,
	SEED_LIST_SENT_AT TIMESTAMP_LTZ NULL,
	SEED_LIST_WILL_SEND_AT TIMESTAMP_LTZ NULL,
	CAMPAIGN_TYPE_KEY INT NULL,
	IS_PRIORITY BOOLEAN NOT NULL,
	SEND_WITHOUT_PREFERENCES BOOLEAN NOT NULL,
	REASON_DISABLED VARCHAR(8000) NULL COLLATE 'en-ci'
);

-- // TABLE 4: CampaignType 
CREATE TABLE IF NOT EXISTS STG.CREO_CAMPAIGNTYPE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    CAMPAIGN_TYPE_KEY INT NOT NULL,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci'
);

-- // TABLE 5: Communication 
CREATE TABLE IF NOT EXISTS STG.CREO_COMMUNICATION_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    COMMUNICATION_KEY INT NOT NULL,
	CAMPAIGN_KEY INT NOT NULL,
	IS_ENABLED BOOLEAN NOT NULL,
	IS_DELETED BOOLEAN NOT NULL,
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL,
	START_TIME TIME NULL,
	END_TIME TIME NULL,
	LIMIT_PER_HOUR INT NULL,
	DATE_START TIMESTAMP_LTZ NULL,
	DATE_END TIMESTAMP_LTZ NULL,
	WEEKDAYS INT NULL,
	TEMPLATE_PATH VARCHAR(8000) NULL COLLATE 'en-ci',
	CONFIG_PATH VARCHAR(8000) NULL COLLATE 'en-ci',
	TYPE SMALLINT NOT NULL,
	ENABLE_QUEUE_BEFORE_DATE_START BOOLEAN NULL,
	IS_PRODUCTION BOOLEAN NOT NULL,
	Provider VARCHAR(8000) NULL COLLATE 'en-ci',
	REASON_DISABLED VARCHAR(8000) NULL COLLATE 'en-ci'
);

-- // TABLE 6: CommunicationMailing 
CREATE TABLE IF NOT EXISTS STG.CREO_COMMUNICATIONMAILING_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    COMMUNICATION_MAILING_KEY INT NOT NULL,
	COMMUNICATION_KEY INT NOT NULL,
	SENT INT NOT NULL,
	QUEUED INT NOT NULL,
	TOTAL INT NOT NULL,
	EXCEPTION INT NOT NULL,
	STATUS INT NOT NULL,
	IS_STALE BOOLEAN NOT NULL,
	DATE_STARTED TIMESTAMP_LTZ NULL,
	DATE_COMPLETED TIMESTAMP_LTZ NULL,
	DATE_UPDATED TIMESTAMP_LTZ NULL 
);

-- // TABLE 7: Config 
CREATE TABLE IF NOT EXISTS STG.CREO_CONFIG_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    CONFIG_KEY INT NOT NULL,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	VALUE VARCHAR(8000) NOT NULL COLLATE 'en-ci'
);

-- // TABLE 8: ConfigHistory 
CREATE TABLE IF NOT EXISTS STG.CREO_CONFIGHISTORY_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    CONFIG_HISTORY_KEY INT NOT NULL,
	CONFIG_KEY INT NOT NULL,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	OLD_VALUE VARCHAR(8000) NULL COLLATE 'en-ci',
	CHANGED_BY VARCHAR(8000) NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL 
);

-- // TABLE 9: ContactType 
CREATE TABLE IF NOT EXISTS STG.CREO_CONTACTTYPE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    CONTACT_TYPE_KEY SMALLINT NOT NULL,
	DESCRIPTION VARCHAR(8000) NOT NULL COLLATE 'en-ci'
);

-- // TABLE 10: Container 
CREATE TABLE IF NOT EXISTS STG.CREO_CONTAINER_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    CONTAINER_KEY INT NOT NULL,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL,
	IS_DELETED BOOLEAN NOT NULL,
	IS_DEPRECATED BOOLEAN NOT NULL 
);

-- // TABLE 11: Dataset 
CREATE TABLE IF NOT EXISTS STG.CREO_DATASET_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DATASET_KEY INT NOT NULL,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL,
	IS_DELETED BOOLEAN NOT NULL,
	CONTAINER_KEY INT NOT NULL,
	ATTRIBUTES INT NOT NULL,
	ROW_COUNT INT NULL,
	ROW_COUNT_UPDATED TIMESTAMP_LTZ NULL 
);

-- // TABLE 12: DatasetColumn 
CREATE TABLE IF NOT EXISTS STG.CREO_DATASETCOLUMN_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DATASET_COLUMN_KEY INT NOT NULL,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci'
);

-- // TABLE 13: Datasource 
CREATE TABLE IF NOT EXISTS STG.CREO_DATASOURCE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DATASOURCE_KEY INT NOT NULL,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	DEFINITION VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	TYPE INT NOT NULL 
);

-- // TABLE 14: DeadMessages 
CREATE TABLE IF NOT EXISTS STG.CREO_DEADMESSAGES_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_KEY BIGINT NOT NULL,
	SUBJECT VARCHAR(8000) NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL,
	DATE_SENT TIMESTAMP_LTZ NULL,
	EXCEPTION VARCHAR(8000) NULL COLLATE 'en-ci',
	CONTAINER_KEY INT NULL,
	COMMUNICATION_MAILING_KEY INT NULL,
	TEMPLATE_KEY INT NULL,
	IS_PRODUCTION BOOLEAN NOT NULL,
	DATASET_ROW_KEY BIGINT NULL,
	SERVER VARCHAR(8000) NULL COLLATE 'en-ci',
	MESSAGE_ID VARCHAR(36) NOT NULL,
	TYPE SMALLINT NULL,
	NUM_EXCEPTIONS INT NOT NULL,
	DELIVERY_STATUS_KEY INT NULL,
	IN_REPLY_TO_MESSAGE_KEY BIGINT NULL,
	DIRECTION SMALLINT NOT NULL,
	SEND_AFTER TIMESTAMP_LTZ NULL,
	SEND_AFTER_MESSAGE_KEY BIGINT NULL,
	IS_FINISHED BOOLEAN NOT NULL 
);

-- // TABLE 15: DeadMessages2 
CREATE TABLE IF NOT EXISTS STG.CREO_DEADMESSAGES2_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_KEY BIGINT NOT NULL,
	SUBJECT VARCHAR(8000) NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL,
	DATE_SENT TIMESTAMP_LTZ NULL,
	EXCEPTION VARCHAR(8000) NULL COLLATE 'en-ci',
	CONTAINER_KEY INT NULL,
	COMMUNICATION_MAILING_KEY INT NULL,
	TEMPLATE_KEY INT NULL,
	IS_PRODUCTION BOOLEAN NOT NULL,
	DATASET_ROW_KEY BIGINT NULL,
	SERVER VARCHAR(8000) NULL COLLATE 'en-ci',
	MESSAGE_ID VARCHAR(36) NOT NULL,
	TYPE SMALLINT NULL,
	NUM_EXCEPTIONS INT NOT NULL,
	DELIVERY_STATUS_KEY INT NULL,
	IN_REPLY_TO_MESSAGE_KEY BIGINT NULL,
	DIRECTION SMALLINT NOT NULL,
	SEND_AFTER TIMESTAMP_LTZ NULL,
	SEND_AFTER_MESSAGE_KEY BIGINT NULL,
	IS_FINISHED BOOLEAN NOT NULL 
);

-- // TABLE 16: DeliveryStatus 
CREATE TABLE IF NOT EXISTS STG.CREO_DELIVERYSTATUS_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DELIVERY_STATUS_KEY INT NOT NULL,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	REFERENCE VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	LIMIT_PER_MESSAGE INT NULL,
	IS_ERROR BOOLEAN NOT NULL,
	IS_FINAL BOOLEAN NOT NULL,
	DESCRIPTION VARCHAR(8000) NULL COLLATE 'en-ci'
);

-- // TABLE 17: Emoji 
CREATE TABLE IF NOT EXISTS STG.CREO_EMOJI_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    EMOJI_KEY INT NOT NULL,
	SHORT_NAME VARCHAR(8000) NULL COLLATE 'en-ci',
	DESCRIPTION VARCHAR(8000) NULL COLLATE 'en-ci',
	CODE VARCHAR(8000) NULL COLLATE 'en-ci'
);

-- // TABLE 18: Folder 
CREATE TABLE IF NOT EXISTS STG.CREO_FOLDER_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    FOLDER_KEY INT NOT NULL,
	NAME VARCHAR(8000) NULL COLLATE 'en-ci',
	CONTAINER_KEY INT NOT NULL,
	PARENT_FOLDER_KEY INT NULL,
	IS_CATCH_ALL BOOLEAN NOT NULL,
	DELETE_AFTER_DAYS INT NULL 
);

-- // TABLE 19: FolderContact 
CREATE TABLE IF NOT EXISTS STG.CREO_FOLDERCONTACT_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    CONTACT_KEY INT NOT NULL,
	FOLDER_KEY INT NOT NULL 
);

-- // TABLE 20: FolderMessage 
CREATE TABLE IF NOT EXISTS STG.CREO_FOLDERMESSAGE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_KEY BIGINT NOT NULL,
	FOLDER_KEY INT NOT NULL,
	LOCKED_BY VARCHAR(8000) NULL COLLATE 'en-ci',
	IS_READ BOOLEAN NOT NULL 
);

-- // TABLE 21: Global 
CREATE TABLE IF NOT EXISTS STG.CREO_GLOBAL_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    APP_VERSION DECIMAL(38,0) NOT NULL 
);

-- // TABLE 22: Log 
CREATE TABLE IF NOT EXISTS STG.CREO_LOG_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    LOG_KEY BIGINT NOT NULL,
	ACTION VARCHAR(8000) NULL COLLATE 'en-ci',
	DESCRIPTION VARCHAR(8000) NULL COLLATE 'en-ci',
	IP_ADDRESS VARCHAR(8000) NULL COLLATE 'en-ci',
	USERNAME VARCHAR(8000) NULL COLLATE 'en-ci',
	RULE_KEY INT NULL,
	TEMPLATE_KEY INT NULL,
	PACKAGE_KEY INT NULL,
	CONTAINER_KEY INT NULL,
	MESSAGE_KEY BIGINT NULL,
	CAMPAIGN_KEY INT NULL,
	COMMUNICATION_KEY INT NULL,
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL,
	SERVER VARCHAR(8000) NULL COLLATE 'en-ci'
);

-- // TABLE 23: MessageContact 
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGECONTACT_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_CONTACT_KEY INT NOT NULL,
	MESSAGE_KEY BIGINT NOT NULL,
	CONTACT_KEY INT NOT NULL,
	TYPE INT NOT NULL 
);

-- // TABLE 24: MessageContactType 
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGECONTACTTYPE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_CONTACT_TYPE_KEY INT NOT NULL,
	DESCRIPTION VARCHAR(8000) NOT NULL COLLATE 'en-ci'
);

-- // TABLE 25: MessagePart 
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGEPART_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_PART_KEY INT NOT NULL,
	MESSAGE_KEY BIGINT NULL,
	CONTENT_TYPE VARCHAR(8000) NULL COLLATE 'en-ci',
	FILENAME VARCHAR(8000) NULL COLLATE 'en-ci',
	DATA VARBINARY NULL,
	IS_COMPRESSED BOOLEAN NOT NULL 
);

-- // TABLE 26: MessageStatusQueue 
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGESTATUSQUEUE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_STATUS_QUEUE_KEY BIGINT NOT NULL,
	DATA VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	DETAIL VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	TYPE INT NOT NULL,
	ENTERED_AT datetime NOT NULL,
	CONTAINER_KEY INT NULL,
	SERVER VARCHAR(8000) NULL COLLATE 'en-ci'
);

-- // TABLE 27: MessageType 
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGETYPE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_TYPE_KEY SMALLINT NOT NULL,
	DESCRIPTION VARCHAR(8000) NOT NULL COLLATE 'en-ci'
);

-- // TABLE 28: Package 
CREATE TABLE IF NOT EXISTS STG.CREO_PACKAGE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    PACKAGE_KEY INT NOT NULL,
	CONTAINER_KEY INT NOT NULL,
	DATE_PUBLISHED TIMESTAMP_LTZ NULL,
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL,
	HASH VARCHAR(8000) NULL COLLATE 'en-ci',
	COMMIT_MESSAGE VARCHAR(8000) NULL COLLATE 'en-ci',
	PUBLISHED_BY VARCHAR(8000) NULL COLLATE 'en-ci'
);

-- // TABLE 29: Parameter 
CREATE TABLE IF NOT EXISTS STG.CREO_PARAMETER_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    PARAMETER_KEY INT NOT NULL,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	DEFINITION VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	DATASOURCE_KEY INT NULL 
);

-- // TABLE 30: Rule 
CREATE TABLE IF NOT EXISTS STG.CREO_RULE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    RULE_KEY INT NOT NULL,
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	PARAMETER_NAME VARCHAR(8000) NULL COLLATE 'en-ci',
	TYPE INT NOT NULL,
	DATE_START TIMESTAMP_LTZ NULL,
	DATE_END TIMESTAMP_LTZ NULL,
	ENABLED BOOLEAN NOT NULL,
	IS_DELETED BOOLEAN NOT NULL,
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL,
	DEFINITION VARCHAR(8000) NULL COLLATE 'en-ci',
	WEIGHT INT NULL,
	CONTAINER_KEY INT NULL 
);

-- // TABLE 31: Template 
CREATE TABLE IF NOT EXISTS STG.CREO_TEMPLATE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    TEMPLATE_KEY INT NOT NULL,
	PATH VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	CONTENT VARBINARY NULL,
	TYPE SMALLINT NOT NULL,
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL,
	DESCRIPTION VARCHAR(8000) NULL COLLATE 'en-ci',
	BASE_TEMPLATE_KEY INT NULL,
	CONTENT_HASH VARCHAR(8000) NULL COLLATE 'en-ci',
	NOTES VARCHAR(8000) NULL COLLATE 'en-ci',
	EDITED_BY VARCHAR(8000) NULL COLLATE 'en-ci'
);

-- // TABLE 32: TemplateRule 
CREATE TABLE IF NOT EXISTS STG.CREO_TEMPLATERULE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    TEMPLATE_KEY INT NOT NULL,
	RULE_KEY INT NOT NULL 
);

-- // TABLE 33: TemplateType 
CREATE TABLE IF NOT EXISTS STG.CREO_TEMPLATETYPE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    TEMPLATE_TYPE_KEY SMALLINT NOT NULL,
	DESCRIPTION VARCHAR(8000) NOT NULL COLLATE 'en-ci'
);

-- // TABLE 34: TempMessage 
CREATE TABLE IF NOT EXISTS STG.CREO_TEMPMESSAGE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    TEMP_MESSAGE_KEY INT NOT NULL,
	Json VARCHAR(8000) NULL COLLATE 'en-ci'
);

-- // TABLE 35: User 
CREATE TABLE IF NOT EXISTS STG.CREO_USER_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    USER_KEY INT NOT NULL,
	USERNAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	NAME VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL 
);

-- // TABLE 36: WebHook 
CREATE TABLE IF NOT EXISTS STG.CREO_WEBHOOK_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    WEBHOOK_KEY INT NOT NULL,
	CONTAINER_KEY INT NOT NULL,
	TYPE INT NOT NULL,
	URL VARCHAR(8000) NOT NULL COLLATE 'en-ci',
	EVENT_NAME VARCHAR(8000) NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL 
);

-- // TABLE 37: DatasetCell 
CREATE TABLE IF NOT EXISTS STG.CREO_DATASETCELL_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DATASET_ROW_KEY BIGINT NOT NULL,
	DATASET_COLUMN_KEY INT NOT NULL,
	DATASET_VALUE_KEY BIGINT NOT NULL 
);

-- // TABLE 38: DatasetValue 
CREATE TABLE IF NOT EXISTS STG.CREO_DATASETVALUE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DATASET_VALUE_KEY BIGINT NOT NULL,
	VALUE VARCHAR(8000) NULL COLLATE 'en-ci',
	VALUE_HASH VARCHAR NULL 
);

-- // TABLE 39: MessageContactV2 
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGECONTACTV2_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_CONTACT_KEY BIGINT NOT NULL,
	MESSAGE_KEY BIGINT NOT NULL,
	CONTACT_KEY INT NOT NULL,
	TYPE INT NOT NULL 
);

-- // TABLE 40: PackageTemplate 
CREATE TABLE IF NOT EXISTS STG.CREO_PACKAGETEMPLATE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    PACKAGE_KEY INT NOT NULL,
	TEMPLATE_KEY INT NOT NULL 
);

-- // TABLE 41: Contact 
CREATE TABLE IF NOT EXISTS STG.CREO_CONTACT_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    CONTACT_KEY INT NOT NULL,
	NAME VARCHAR(8000) NULL COLLATE 'en-ci',
	ADDRESS VARCHAR(8000) NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL,
	CONTACT_TYPE SMALLINT NOT NULL,
	IS_EXPIRED BOOLEAN NOT NULL,
	NUM_ERRORS INT NOT NULL,
	IS_INVALID BOOLEAN NOT NULL 
);

-- // TABLE 42: MessageDeliveryStatus 
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGEDELIVERYSTATUS_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_DELIVERY_STATUS_KEY BIGINT NOT NULL,
	MESSAGE_KEY BIGINT NOT NULL,
	DELIVERY_STATUS_KEY INT NOT NULL,
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL,
	DETAIL VARCHAR NULL COLLATE 'en-ci'
);

-- // TABLE 43: MessagePartV2 
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGEPARTV2_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_PART_KEY BIGINT NOT NULL,
	MESSAGE_KEY BIGINT NULL,
	CONTENT_TYPE VARCHAR(8000) NULL COLLATE 'en-ci',
	FILENAME VARCHAR(8000) NULL COLLATE 'en-ci',
	DATA VARCHAR NULL 
);

-- // TABLE 44: Message 
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_KEY BIGINT NOT NULL,
	SUBJECT VARCHAR(8000) NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL,
	DATE_SENT TIMESTAMP_LTZ NULL,
	EXCEPTION VARCHAR NULL COLLATE 'en-ci',
	CONTAINER_KEY INT NULL,
	COMMUNICATION_MAILING_KEY INT NULL,
	TEMPLATE_KEY INT NULL,
	IS_PRODUCTION BOOLEAN NOT NULL,
	DATASET_ROW_KEY BIGINT NULL,
	SERVER VARCHAR(8000) NULL COLLATE 'en-ci',
	MESSAGE_ID VARCHAR(36) NOT NULL,
	TYPE SMALLINT NULL,
	NUM_EXCEPTIONS INT NOT NULL,
	DELIVERY_STATUS_KEY INT NULL,
	IN_REPLY_TO_MESSAGE_KEY BIGINT NULL,
	DIRECTION SMALLINT NOT NULL,
	SEND_AFTER TIMESTAMP_LTZ NULL,
	SEND_AFTER_MESSAGE_KEY BIGINT NULL,
	IS_FINISHED BOOLEAN NOT NULL,
	HEADERS VARCHAR NULL COLLATE 'en-ci',
	VENDOR_ID VARCHAR(8000) NULL COLLATE 'en-ci'
);
