dag_id: 'Staging_CM'
schedule_interval: '0 6 * * *'
catchup: False

TABLE_LIST: ['PRESENTMENTREQUEST', 'OPENENDLOANSTATEMENT', 'INSURANCEENROLLMENT', 'LOANFUNDING', 'OFFERACCEPTED', 'AVAILABLEOFFER', 'TRANSDETAIL', 'ACH_HISTORY', 'COMPANY', 'CREDITCARDATTEMPTS', 'CREDITCARDRESULTCODE', 'CREDITCARDTRANS', 'CUSTOMER', 'CUSTOMERADDRESS', 'CUSTOMERINCOME', 'LOANAPPLICATION', 'LOANPAYMENT', 'LOANPRODUCT', 'LOANPRODUCTCONFIG', 'MPAYINTEREST', 'OPENENDINTEREST', 'PRESENTMENT', 'PROMISETOPAY', 'RBCEFUNDBATCH', 'SPAYINTEREST', 'SERVICETRANS', 'SERVICEDETAIL', 'CASHEDCHECK', 'BALSHEET2', 'ENDOFDAYRPT', 'LOAN', 'CAPSRUN', 'CREDITCARDVENDOR', 'CURRENCY', 'DISTRICT', 'ACH_SENT', 'LOANFUNDINGSTATUS', 'LOANPRODUCTFINANCIALGROUP', 'MARKETS', 'PRESENTMENTCREDITCARDTRANSXREF', 'PRESENTMENTTYPE', 'PROMISETOPAYDETAIL', 'REGION', 'OPENENDLOANSTATEMENTBALANCE', 'TELLERID', 'SECURITYGROUPHISTORY', 'BALSHEET_TRANSDETAIL', 'ENDOFDAYINVENTORYDETAIL', 'LOANINCOME', 'LOANPAYMENTMPAY', 'LOANPAYMENTOPENEND', 'LOANPAYMENTSPAY', 'MPAYAMORT', 'MPAYLOAN', 'OPENENDLOAN', 'PRESENTMENTREQUESTACHHISTORYXREF', 'TRANSCODE', 'RBCEFUNDBATCHDETAIL', 'RISREPT', 'SPAYLOAN', 'TRANSDETAILACCT']
DATABASE_NAME: 'CM'
FILE_FORMAT: 'FORMAT_NAME = STG.LD_CSV_PIPE_SH0_EON_GZ'
COL_SEP: '|'
AS_OF_DATE: '2023-07-01'
METADATA_FILENAME: 'FILENAME'

MSSQL_CONN_ID: 'awsmssql_cansql_winchkcan_conn'
S3_CONN_ID: 'aws_s3_conn'
SNOWFLAKE_CONN_ID: 'snowflake_default'
