dag_id: 'Staging_CREO'
schedule_interval: '0 6 * * *'
catchup: False

TABLE_LIST: ["APPROVALREQUEST", "APPROVALREQUESTITEM", "CAMPAIGN", "CAMPAIGNTYPE", "COMMUNICATION", "COMMUNICATIONMAILING", "CONFIG", "CONFIGHISTORY", "CONTACT", "CONTACTTYPE", "CONTAINER", "DATASET", "DATASETCELL", "DATASETCOLUMN", "DATASETROW", "DATASETVALUE", "DATASOURCE", "DEADMESSAGES", "DEADMESSAGES2", "DELIVERYSTATUS", "EMOJI", "FOLDER", "FOLDERCONTACT", "FOLDERMESSAGE", "GLOBAL", "LOG", "MESSAGE", "MESSAGECONTACT", "MESSAGECONTACTTYPE", "MESSAGECONTACTV2", "MESSAGEDELIVERYSTATUS", "MESSAGEPART", "MESSAGEPARTV2", "MESSAGESTATUSQUEUE", "MESSAGETYPE", "PACKAGE", "PACKAGETEMPLATE", "PARAMETER", "RULE", "TEMPLATE", "TEMPLATERULE", "TEMPLATETYPE", "TEMPMESSAGE", "USER", "WEBHOOK"]
DATABASE_NAME: 'CREO'

COL_SEP: '|'
LINE_SEP: '\n'
# FILE_FORMAT: 'FORMAT_NAME = STG.LD_CSV_PIPE_SH0_EON_GZ'
FILE_FORMAT: "
TYPE = CSV \n
COMPRESSION = AUTO \n
FIELD_DELIMITER = '|' \n
RECORD_DELIMITER = '\\n' \n
SKIP_HEADER = 0 \n
REPLACE_INVALID_CHARACTERS = TRUE
"

AS_OF_DATE: '2023-07-01'
METADATA_FILENAME: 'METADATAFILENAME'

MSSQL_CONN_ID: 'awsmssql_creosql_creo_conn'
S3_CONN_ID: 'aws_s3_conn'
SNOWFLAKE_CONN_ID: 'snowflake_default'
