
-- // TABLE 1: DatasetCell 
-- DROP TABLE IF EXISTS STG.CREO_DATASETCELL_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_DATASETCELL_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DATASET_ROW_KEY BIGINT NOT NULL,
	DATASET_COLUMN_KEY INT NOT NULL,
	DATASET_VALUE_KEY BIGINT NOT NULL 
);

-- // TABLE 2: DatasetRow 
-- DROP TABLE IF EXISTS STG.CREO_DATASETROW_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_DATASETROW_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    DATASET_ROW_KEY BIGINT NOT NULL,
	DATASET_KEY INT NOT NULL,
	HAS_MESSAGE BOOLEAN NOT NULL 
);

-- // TABLE 3: Global 
-- DROP TABLE IF EXISTS STG.CREO_GLOBAL_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_GLOBAL_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    APP_VERSION DECIMAL(38,0) NOT NULL 
);

-- // TABLE 4: Message 
-- DROP TABLE IF EXISTS STG.CREO_MESSAGE_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGE_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_KEY BIGINT NOT NULL,
	SUBJECT VARCHAR(8000) NULL COLLATE 'en-ci',
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL,
	DATE_SENT TIMESTAMP_LTZ NULL,
	EXCEPTION VARCHAR NULL COLLATE 'en-ci',
	CONTAINER_KEY INT NULL,
	COMMUNICATION_MAILING_KEY INT NULL,
	TEMPLATE_KEY INT NULL,
	IS_PRODUCTION BOOLEAN NOT NULL,
	DATASET_ROW_KEY BIGINT NULL,
	SERVER VARCHAR(8000) NULL COLLATE 'en-ci',
	MESSAGE_ID VARCHAR(36) NOT NULL,
	TYPE SMALLINT NULL,
	NUM_EXCEPTIONS INT NOT NULL,
	DELIVERY_STATUS_KEY INT NULL,
	IN_REPLY_TO_MESSAGE_KEY BIGINT NULL,
	DIRECTION SMALLINT NOT NULL,
	SEND_AFTER TIMESTAMP_LTZ NULL,
	SEND_AFTER_MESSAGE_KEY BIGINT NULL,
	IS_FINISHED BOOLEAN NOT NULL,
	HEADERS VARCHAR NULL COLLATE 'en-ci',
	VENDOR_ID VARCHAR(8000) NULL COLLATE 'en-ci'
);

-- // TABLE 5: MessageContactV2 
-- DROP TABLE IF EXISTS STG.CREO_MESSAGECONTACTV2_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGECONTACTV2_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_CONTACT_KEY BIGINT NOT NULL,
	MESSAGE_KEY BIGINT NOT NULL,
	CONTACT_KEY INT NOT NULL,
	TYPE INT NOT NULL 
);

-- // TABLE 6: MessageDeliveryStatus 
-- DROP TABLE IF EXISTS STG.CREO_MESSAGEDELIVERYSTATUS_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGEDELIVERYSTATUS_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_DELIVERY_STATUS_KEY BIGINT NOT NULL,
	MESSAGE_KEY BIGINT NOT NULL,
	DELIVERY_STATUS_KEY INT NOT NULL,
	DATE_ENTERED TIMESTAMP_LTZ NOT NULL,
	DETAIL VARCHAR NULL COLLATE 'en-ci'
);

-- // TABLE 7: MessagePartV2 
-- DROP TABLE IF EXISTS STG.CREO_MESSAGEPARTV2_HIST;
CREATE TABLE IF NOT EXISTS STG.CREO_MESSAGEPARTV2_HIST ( 
    METADATAFILENAME VARCHAR(16777216) NOT NULL COLLATE 'en-ci', LOADTIMESTAMP TIMESTAMP_NTZ(9) NOT NULL, ASOFDATE DATE,
    MESSAGE_PART_KEY BIGINT NOT NULL,
	MESSAGE_KEY BIGINT NULL,
	CONTENT_TYPE VARCHAR(8000) NULL COLLATE 'en-ci',
	FILENAME VARCHAR(8000) NULL COLLATE 'en-ci',
	DATA VARBINARY NULL 
);
