CREATE OR REPLACE TABLE ARES.STG.CREO_APPROVALREQUEST_HIST
CLONE ZEUS.STG.CREO_APPROVALREQUEST_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_APPROVALREQUESTITEM_HIST
CLONE ZEUS.STG.CREO_APPROVALREQUESTITEM_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_CAMPAIGN_HIST
CLONE ZEUS.STG.CREO_CAMPAIGN_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_CAMPAIGNTYPE_HIST
CLONE ZEUS.STG.CREO_CAMPAIGNTYPE_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_COMMUNICATION_HIST
CLONE ZEUS.STG.CREO_COMMUNICATION_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_COMMUNICATIONMAILING_HIST
CLONE ZEUS.STG.CREO_COMMUNICATIONMAILING_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_CONFIG_HIST
CLONE ZEUS.STG.CREO_CONFIG_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_CONFIGHISTORY_HIST
CLONE ZEUS.STG.CREO_CONFIGHISTORY_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_CONTACTTYPE_HIST
CLONE ZEUS.STG.CREO_CONTACTTYPE_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_CONTAINER_HIST
CLONE ZEUS.STG.CREO_CONTAINER_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_DATASET_HIST
CLONE ZEUS.STG.CREO_DATASET_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_DATASETCOLUMN_HIST
CLONE ZEUS.STG.CREO_DATASETCOLUMN_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_DATASOURCE_HIST
CLONE ZEUS.STG.CREO_DATASOURCE_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_DEADMESSAGES_HIST
CLONE ZEUS.STG.CREO_DEADMESSAGES_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_DEADMESSAGES2_HIST
CLONE ZEUS.STG.CREO_DEADMESSAGES2_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_DELIVERYSTATUS_HIST
CLONE ZEUS.STG.CREO_DELIVERYSTATUS_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_EMOJI_HIST
CLONE ZEUS.STG.CREO_EMOJI_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_FOLDER_HIST
CLONE ZEUS.STG.CREO_FOLDER_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_FOLDERCONTACT_HIST
CLONE ZEUS.STG.CREO_FOLDERCONTACT_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_FOLDERMESSAGE_HIST
CLONE ZEUS.STG.CREO_FOLDERMESSAGE_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_GLOBAL_HIST
CLONE ZEUS.STG.CREO_GLOBAL_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_LOG_HIST
CLONE ZEUS.STG.CREO_LOG_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_MESSAGECONTACT_HIST
CLONE ZEUS.STG.CREO_MESSAGECONTACT_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_MESSAGECONTACTTYPE_HIST
CLONE ZEUS.STG.CREO_MESSAGECONTACTTYPE_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_MESSAGEPART_HIST
CLONE ZEUS.STG.CREO_MESSAGEPART_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_MESSAGESTATUSQUEUE_HIST
CLONE ZEUS.STG.CREO_MESSAGESTATUSQUEUE_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_MESSAGETYPE_HIST
CLONE ZEUS.STG.CREO_MESSAGETYPE_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_PACKAGE_HIST
CLONE ZEUS.STG.CREO_PACKAGE_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_PARAMETER_HIST
CLONE ZEUS.STG.CREO_PARAMETER_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_RULE_HIST
CLONE ZEUS.STG.CREO_RULE_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_TEMPLATE_HIST
CLONE ZEUS.STG.CREO_TEMPLATE_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_TEMPLATERULE_HIST
CLONE ZEUS.STG.CREO_TEMPLATERULE_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_TEMPLATETYPE_HIST
CLONE ZEUS.STG.CREO_TEMPLATETYPE_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_TEMPMESSAGE_HIST
CLONE ZEUS.STG.CREO_TEMPMESSAGE_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_USER_HIST
CLONE ZEUS.STG.CREO_USER_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_WEBHOOK_HIST
CLONE ZEUS.STG.CREO_WEBHOOK_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_DATASETCELL_HIST
CLONE ZEUS.STG.CREO_DATASETCELL_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_DATASETROW_HIST
CLONE ZEUS.STG.CREO_DATASETROW_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_MESSAGECONTACTV2_HIST
CLONE ZEUS.STG.CREO_MESSAGECONTACTV2_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_PACKAGETEMPLATE_HIST
CLONE ZEUS.STG.CREO_PACKAGETEMPLATE_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_CONTACT_HIST
CLONE ZEUS.STG.CREO_CONTACT_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_MESSAGEDELIVERYSTATUS_HIST
CLONE ZEUS.STG.CREO_MESSAGEDELIVERYSTATUS_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_MESSAGEPARTV2_HIST
CLONE ZEUS.STG.CREO_MESSAGEPARTV2_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_MESSAGE_HIST
CLONE ZEUS.STG.CREO_MESSAGE_HIST;

CREATE OR REPLACE TABLE ARES.STG.CREO_DATASETVALUE_HIST
CLONE ZEUS.STG.CREO_DATASETVALUE_HIST;
