SELECT pt.PACKAGE_KEY, pt.TEMPLATE_KEY
FROM [dbo].PACKAGETEMPLATE pt
LEFT JOIN [dbo].TEMPLATE t
    ON pt.TEMPLATE_KEY = t.TEMPLATE_KEY
LEFT JOIN [dbo].PACKAGE p
    ON pt.PACKAGE_KEY = p.PACKAGE_KEY
WHERE CAST(p.DATE_ENTERED AS DATE) = CAST('{asOfDate}' AS DATE)
OR CAST(t.DATE_ENTERED AS DATE) = CAST('{asOfDate}' AS DATE);
