select
AVAILABLE_OFFER_KEY,
OFFER_TYPE_KEY,
CUSTOMER_KEY,
VISITOR_KEY,
LOAN_KEY,
OFFER_META_DATA,
CAST(DATE_ENTERED AS DATE) AS DATE_ENTERED,
ENTERED_BY
FROM dbo.AvailableOffer
WHERE CAST(DATE_ENTERED AS DATE) = cast('{asOfDate}' as date)
;
