select
OFFER_ACCEPTED_KEY,
OFFER_TYPE_KEY,
CUSTOMER_KEY,
VISITOR_KEY,
LOAN_KEY,
OFFER_META_DATA,
CAST(DATE_ENTERED AS DATE) AS DATE_ENTERED,
ENTERED_BY,
CAST(DATE_ACCEPTED as DATE) AS DATE_ACCEPTED
FROM dbo.OfferAccepted
WHERE CAST(DATE_ENTERED AS DATE) = cast('{asOfDate}' as date)