/*
[dbo].FOLDERCONTACT
CONTACT_KEY,FOLDER_KEY
Join CONTACT on CONTACT_KEY, get DATE_ENTERED

SELECT  COUNT(*) -- 122
    -- fc.CONTACT_KEY, fc.FOLDER_KEY
FROM [dbo].FOLDERCONTACT fc
LEFT JOIN [dbo].CONTACT c
ON fc.CONTACT_KEY = c.CONTACT_KEY
WHERE fc.CONTACT_KEY IS NOT NULL 
AND fc.FOLDER_KEY IS NOT NULL;
*/

SELECT fc.CONTACT_KEY, fc.FOLDER_KEY
FROM [dbo].FOLDERCONTACT fc
LEFT JOIN [dbo].CONTACT c
ON fc.CONTACT_KEY = c.CONTACT_KEY
WHERE CAST([c.DATE_ENTERED] AS DATE) = CAST('{asOfDate}' AS DATE);
