/*
[dbo].TEMPLATERULE
TEMPLATE_KEY,RULE_KEY
Join TEMPLATE on TEMPLATE_KEY, get DATE_ENTERED
Join RULE on RULE_KEY, get DATE_ENTERED

SELECT COUNT(*) -- 600
FROM [dbo].TEMPLATERULE tr
LEFT JOIN [dbo].TEMPLATE t
    ON tr.TEMPLATE_KEY = t.TEMPLATE_KEY
LEFT JOIN [dbo].[RULE] r
    ON tr.RULE_KEY = r.RULE_KEY
WHERE tr.RULE_KEY IS NOT NULL 
AND tr.TEMPLATE_KEY IS NOT NULL;
*/



SELECT tr.RULE_KEY, tr.TEMPLATE_KEY
FROM [dbo].TEMPLATERULE tr
LEFT JOIN [dbo].TEMPLATE t
    ON tr.TEMPLATE_KEY = t.TEMPLATE_KEY
LEFT JOIN [dbo].[RULE] r
    ON tr.RULE_KEY = r.RULE_KEY
WHERE CAST([r.DATE_ENTERED] AS DATE) = CAST('{asOfDate}' AS DATE)
OR CAST([t.DATE_ENTERED] AS DATE) = CAST('{asOfDate}' AS DATE);
