dag_id: 'Staging_LD_Utils'
schedule_interval: '@once'
catchup: False

MSSQL_CONN_ID: 'awsmssql_canldsql_winchkcanld_conn'
S3_CONN_ID: 'aws_s3_conn'
SNOWFLAKE_CONN_ID: 'snowflake_default'

SNOWFLAKE_DATABASE: 'ARES'
SNOWFLAKE_SCHEMA: 'ETL'
MSSQL_DATABASE: 'LD'
